config/routes.rb
Rails.application.routes.draw do
  resources :lodes
  resources :profiles

  devise_for :users
  resources :items do
    member do
      get :selectResource
      get :removeResource
    end
  end

  resources :resources

  get 'home/index'

  root 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  # mount_uploader :linkPhoto, PictureUploader
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  
  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:firstName, :lastName, :linkPhoto, :linkGoogle, :dob, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstName %>
    <%= f.input :lastName %>
    <%= f.file_field :linkPhoto %>
    <!-- <%= f.input :linkPhoto %> -->
    <%= f.input :linkGoogle %>
    <%= f.input :dob, start_year: Date.today.year - 16, end_year: Date.today.year - 60%>
    <!-- <%= f.association :user %> -->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Linkphoto</th>
      <th>Linkgoogle</th>
      <th>Dob</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstName %></td>
        <td><%= profile.lastName %></td>
        <td><%= profile.linkPhoto %></td>
        <td><%= profile.linkGoogle %></td>
        <td><%= profile.dob %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <%= image_tag @profile.linkPhoto, width:"200px", class: 'img-circle' %><br>
    <%= link_to @profile.firstName + " " + @profile.lastName, @profile.linkGoogle %><br>
    <%= @profile.dob %>
  </div>
</div>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>