config/routes.rb
Rails.application.routes.draw do
  resources :lodes
  resources :profiles

  devise_for :users
  resources :items do
    member do
      get :selectResource
      get :removeResource
    end
  end

  resources :resources

  get 'home/index'

  root 'home#index'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-12 resource-desc">
    <% if @resource %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-6">
              <%= f.file_field :image, type: :file %>
              <%= f.text_field :name, placeholder: "Name" %><br>
              <% if @resourceTypes %>
              <%= f.collection_select :resourceType, @resourceTypes, :resourceType, :resourceType, include_blank: true %>
              <% else %>
              <%= f.text_field :resourceType, placeholder: "Resource type" %>
              <% end %>
            </div>
            <div class="col-md-6">
              TTValue: <%= f.text_field :ttValue %><br>
              MarketValue: <%= f.text_field :marketValue %><br> 
              <%= f.submit %>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="col-md-6">
            description
          </div>
          <div class="col-md-6">
             
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
  
<% end %>

app/views/resources/_resourcePanel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <% if @resource %>
        <div class="col-md-6">

          <% if @resource.image %>
            <%= image_tag @resource.image, width:"100px", height:"100px"%>
          <% else %>
            <%= image_tag "questionMark.png", width:"100px", height:"100px"%>
          <% end %>
          <%= @resource.name %> (<%= @resource.resourceType %>)
          
        </div>
        <div class="col-md-6">
          TTValue: <%= @resource.ttValue %><br>
          MarketValue: <%= @resource.marketValue %><br>
        </div>
      <% else %>
        <div class="col-md-6">

          <% if resource.image %>
            <%= image_tag resource.image, width:"100px", height:"100px"%>
          <% else %>
            <%= image_tag "questionMark.png", width:"100px", height:"100px"%>
          <% end %>
          <%= resource.name %> (<%= resource.resourceType %>)
        </div>
        <div class="col-md-6">
          TTValue: <%= resource.ttValue %><br>
          MarketValue: <%= resource.marketValue %><br>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<div class="row">
  <div class="col-md-4 resource-list">
    <%= link_to '+', new_resource_path, class:'btn btn-info' %><%= link_to '+', new_lode_path(resource: @resource.id), class:'btn btn-default pull-right' %><br>
      <p>
        <% if @resources %>  
          <% @resources.order(name: :asc).each do |resource| %>
            <li>
              <%= link_to resource.name, resources_path(resource: resource.id) %>
              <% if current_user.id == 1%>
                <%= link_to 'x', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </p>
      <% if @resource %>
        <%= render "resources/resourcePanel" %>
    <% end %>
  </div>
  <div class="col-md-8 resource-desc">
    <%= image_tag "eudoria-v3-0.jpg", width:"100%", height:"100%"%>
  </div>
</div>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @resource.resourceType %>
</p>

<p>
  <strong>Type:</strong>
  <%= @resource.image %>
</p>
<p>
  <strong>Ttvalue:</strong>
  <%= @resource.ttValue %>
</p>

<p>
  <strong>Marketvalue:</strong>
  <%= @resource.marketValue %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>