config/routes.rb
Rails.application.routes.draw do
  resources :lodes
  resources :profiles

  devise_for :users
  resources :items do
    member do
      get :selectResource
      get :removeResource
    end
  end

  resources :resources

  get 'home/index'

  root 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates_presence_of :name, uniqueness: true
  has_many :recipes
  has_many :resources, through: :recipes
  mount_uploader :image, PictureUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :selectResource, :removeResource]
  respond_to :html, :xml, :json
  # GET /items
  # GET /items.json

  def selectResource
    if params[:resource]
      @selectedResource = Resource.find(params[:resource])
      @item.resources << @selectedResource
    end
    redirect_to :back
  end

  def removeResource
    if params[:resource]
      @item.resources.delete(params[:resource])
    end
    redirect_to :back
  end

  def index
    @items = Item.all

    if params[:item_id]
      @item = Item.find(params[:item_id])
    else
      @item = Item.last
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @resources = Resource.all

    if params[:resource]
      @resource = Resource.find(params[:resource])
    end
  end
 
  # GET /items/new
  def new
    @item = Item.new
    @itemTypes = Item.order(:itemType)
    @resources = Resource.all
  end

  # GET /items/1/edit
  def edit
    # @itemTypes = ['Components', 'Weapon', 'Tool']
    @itemTypes = Item.order(:itemType)
    @resources = Resource.all
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    # @item.resources << :resource_id

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :itemType, :level, :ttValue, :marketValue, :volume, :image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
 <div class="row field">
  <%= simple_form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-6">
            
            <%= f.file_field :image, type: :file %><br>
            <%= f.text_field :name, placeholder: "Name" %><br>
            <%= hidden_field_tag :image_cache %>

            <% if current_user.id == 1 %>
              <%= f.text_field :itemType, placeholder: "Item type" %><br>
            <% else %>
              <%= f.collection_select :itemType, @itemTypes, :id, :itemType, include_blank: false %><br>
            <% end %>
            <%= f.text_field :level, placeholder: "Level" %><br>
          </div>
          <div class="col-md-6">
            
            <%= f.text_field :ttValue, placeholder: "TTValue" %><br>
            <%= f.text_field :marketValue, placeholder: "Market Value" %><br>
            <%= f.number_field :volume, placeholder: "Volume" %><br>
          </div>
        </div>
      </div>
  
    
    <%= f.submit %>
  </div>
  
<% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="row">
  <div class="col-md-4 resource-list">
    <h3>Items</h3><%= link_to '+', new_item_path, class:'btn btn-success pull-right' %><br>
      <p>
        <% if @items %>  
          <% @items.order(name: :asc).each do |item| %>
            <li>
              <%= link_to item.name, items_path(item_id: item.id) %>
              <% if current_user.id == 1%>
                <%= link_to 'x', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </p>
  </div>
  <div class="col-md-8 resource-desc">
    <div class="row">
      <div class="col-md-12">
        <% if @item %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="row">
                <div class="col-md-3">
                  <% if @item.image %>
                    <%= cl_image_tag @item.image.url, width:"100px", height:"100px"%>
                  <% else %>
                    <%= image_tag "questionMark.png", width:"100px", height:"100px"%>
                  <% end %>
                </div>
                <div class="col-md-3">
                  <%= link_to @item.name, item_path(@item) %><br>
                  (<%= @item.itemType %> - <%= @item.level %>)
                </div>
                <div class="col-md-3">
                Volume: <%= @item.volume %><br>
                Market Value: <%= @item.marketValue %><br>
                
                Cost: <%= @item.resources.sum(:ttValue).round(3) %><br>
                
                </div>
                <div class="col-md-3">
                APpA: <br>
                TTvalue: <%= @item.ttValue %><br>
                Market Cost: <br>
                </div>
              </div>
            </div>
            <div class="panel-body">
              description
            </div>
            <div class="panel-footer">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Cost</th>
                    <th>Market Value</th>
                  </tr>
                </thead>

                <tbody>
                <% @item.resources.each do |resource| %>
                  <tr>
                    <td><%= image_tag resource.image.url, width:"50px", height:"50px" %></td>
                    <td><%= link_to resource.name, resources_path(resource: resource) %></td>
                    <td><%= resource.ttValue %></td>
                    <td>
                      <% if resource.marketValue %>
                        <%= resource.marketValue %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
      </div>
    </div>

      <% end %>
  </div>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            <% if @item.image %>
              <%= image_tag @item.image, width:"100px", height:"100px"%>
            <% else %>
              <%= image_tag "questionMark.png", width:"100px", height:"100px"%>
            <% end %>
            <%= @item.name %><br>
            (<%= @item.itemType %> - <%= @item.level %>)
            <% if current_user.id == 1%>
              <%= link_to "(Edit)", edit_resource_path(@item)%>
            <% end %>
            
          </div>
          <div class="col-md-12">
            TTValue: <%= @item.ttValue %><br>
            Cost: <%= @item.resources.sum(:ttValue).round(3) %><br>
            MarketValue: <%= @item.marketValue %><br>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <% if current_user.id == 1 %>
    <div class="panel panel-default">
      <div class="panel-heading">
        Used resources
      </div>

      <div class="panel-body">
        <% @resources.each do |resource| %>
          <% if @item.resources.include? resource %>
            <%= link_to resource.name, removeResource_item_path(@item, resource: resource), class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        Resources
      </div>
      <div class="panel-body">
        <% @resources.each do |resource| %>
          <% if !@item.resources.include? resource %>
            <%= link_to resource.name, selectResource_item_path(@item, resource: resource), class: 'btn btn-success' %>
          <% end %>
        <% end %>
      </div>
    </div>

    <% else %>

      <% @resources.each do |resource| %>
        <% if @item.resources.include? resource %>
          <%= render "resources/resourcePanel", resource: resource %>
          <%# link_to resource.name, resource_path(resource), class: 'btn btn-danger' %>
        <% end %>
      <% end %>

    <% end %>

  </div>
</div>