config/routes.rb
Rails.application.routes.draw do
  resources :lodes
  resources :profiles

  devise_for :users
  resources :items do
    member do
      get :selectResource
      get :removeResource
    end
  end

  resources :resources

  get 'home/index'

  root 'home#index'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Entropia Stats</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "Crafting", items_path, class: 'btn btn-warning'%></li>
        <li><%= link_to "Hunting", items_path, class: 'btn btn-danger disabled'%></li>
        <li><%= link_to "Mining", resources_path, class: 'btn btn-info'%></li>
        <li><%= link_to "Lodes", lodes_path, class: 'btn btn-default'%></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.profile %>
            <li><%= link_to current_user.profile.firstName, profile_path(current_user.id) %></li>
            <li><%= link_to 'X', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %></li>
          <% else %>
            <li><%= link_to "Profile", new_profile_path %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EntropiaStats</title>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<!-- allow mobile view on mobile -->
<meta name="viewport" content="width=device-width", user-scalable="no", initial-scale=1>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

	<%= render "layouts/navbar" %>
	<div class="row">
		<div class="col-md-2">

			<% if user_signed_in? && current_user.id != 1%>
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- entropiaStatsLeft -->
			<ins class="adsbygoogle"
		    style="display:block"
		    data-ad-client="ca-pub-1350672881569046"
		    data-ad-slot="3694956653"
		    data-ad-format="auto"></ins>
			<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
			</script>
			<% end %>
		</div>
		<div class="col-md-8">
			<%= yield %>
		</div>
		<div class="col-md-2">
		<% if user_signed_in? && current_user.id != 1%>
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- entropiaStatsRight -->
			<ins class="adsbygoogle"
			     style="display:block"
			     data-ad-client="ca-pub-1350672881569046"
			     data-ad-slot="2578150259"
			     data-ad-format="auto"></ins>
			<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
			</script>
			<% end %>
		</div>
	</div>

</body>
</html>